"""add lists tables

Revision ID: adbeebaefcab
Revises: 37b13892692b
Create Date: 2023-12-23 16:32:34.888441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adbeebaefcab'
down_revision: Union[str, None] = '37b13892692b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lists')),
    sa.UniqueConstraint('id', name=op.f('uq_lists_id'))
    )
    op.create_table('list_company',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_list_company_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_list_company_list_id_lists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_list_company')),
    sa.UniqueConstraint('id', name=op.f('uq_list_company_id'))
    )
    op.create_unique_constraint(op.f('uq_ceo_id'), 'ceo', ['id'])
    op.create_unique_constraint(op.f('uq_comments_id'), 'comments', ['id'])
    op.create_unique_constraint(op.f('uq_companies_id'), 'companies', ['id'])
    op.create_unique_constraint(op.f('uq_financials_id'), 'financials', ['id'])
    op.create_unique_constraint(op.f('uq_forecasts_id'), 'forecasts', ['id'])
    op.create_unique_constraint(op.f('uq_forecasts_fields_id'), 'forecasts_fields', ['id'])
    op.create_unique_constraint(op.f('uq_prices_id'), 'prices', ['id'])
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_prices_id'), 'prices', type_='unique')
    op.drop_constraint(op.f('uq_forecasts_fields_id'), 'forecasts_fields', type_='unique')
    op.drop_constraint(op.f('uq_forecasts_id'), 'forecasts', type_='unique')
    op.drop_constraint(op.f('uq_financials_id'), 'financials', type_='unique')
    op.drop_constraint(op.f('uq_companies_id'), 'companies', type_='unique')
    op.drop_constraint(op.f('uq_comments_id'), 'comments', type_='unique')
    op.drop_constraint(op.f('uq_ceo_id'), 'ceo', type_='unique')
    op.drop_table('list_company')
    op.drop_table('lists')
    # ### end Alembic commands ###
